export const products = [{
    "author": ["Hector Garcia", "Francesc Miralles"],
    "narratedBy": ["Trovi"],
    "genre": ["Self-help"],
    "reviews": ["5f8fd1b6879113f1d3afe00bpranav07092k@gmail.com"],
    "_id": "5f8fd1b6879113f1d3afe00b",
    "programType": "Audio-Book",
    "rating": 4,
    "totalReviewPoint": 4,
    "totalReview": 1,
    "sampleUri": null,
    "bookUri": null,
    "listenerCount": 0,
    "length": 120,
    "language": "English",
    "publisher": "Trovi Publications",
    "category": "non-fiction",
    "title": "Ikigai",
    "imageUri": "https://res.cloudinary.com/trovi/image/upload/v1602555356/ikigai_cccpph.jpg",
    "price": 500,
    "summary": "Brought to you by Penguin.<br/> The international bestseller.<br/> We all have an ikigai.<br/> It's the Japanese word for ‘a reason to live’ or ‘a reason to jump out of bed in the morning’.<br/> It’s the place where your needs, desires, ambitions and satisfaction meet. A place of balance. Small wonder that finding your ikigai is closely linked to living longer.<br/> Finding your ikigai is easier than you might think. This audiobook will help you work out what your own ikigai really is and equip you to change your life. You have a purpose in this world: your skills, your interests, your desires and your history have made you the perfect candidate for something. All you have to do is find it.<br/> Do that and you can make every single day of your life joyful and meaningful.<br/> PLEASE NOTE: When you purchase this title, the accompanying reference material will be available in your Library section along with the audio on our desktop site.<br/> ©2017 Francesc Miralles and Héctor García (P)2017 Random House Audiobooks<br/>"
}, {
    "author": ["Mel Robbins"],
    "narratedBy": ["Trovi"],
    "genre": ["Self-help"],
    "reviews": [],
    "_id": "5f8fd1b6879113f1d3afe00c",
    "programType": "Audio-Book",
    "rating": null,
    "totalReviewPoint": 0,
    "totalReview": 0,
    "sampleUri": null,
    "bookUri": null,
    "listenerCount": 0,
    "length": 120,
    "language": "English",
    "publisher": "Trovi Publications",
    "category": "non-fiction",
    "title": "Take Control of Your Life",
    "imageUri": "https://res.cloudinary.com/trovi/image/upload/v1602555354/takeControlOfYourLife_p4zl4q.jpg",
    "price": 500,
    "summary": "Mel Robbins is back! The international bestselling phenomenon and creator of The Five Second Rule and Kick Ass with Mel Robbins returns to help you tackle the single biggest obstacle you face: fear. This life-changing Audible Original features a powerful mix of one-on-one life-coaching sessions and a personal narrative with vital take-aways that you can start using immediately. <br/> With humor and wisdom, Mel Robbins expertly tackles the fear of change, rejection, and being alone, as well as imposter syndrome and feeling trapped in the wrong career. Each session is a goldmine of discovery as Mel guides you to find your purpose, improve your relationships, and ultimately take control of your life. In these times of high anxiety, it’s easy to feel overwhelmed - that changes right now. If you want the tools to break free from fear and live to your fullest potential, this is a must-listen.<br/> PLEASE NOTE: When you purchase this title, the accompanying PDF will be available in your Audible Library along with the audio.<br/> ©2019 Mel Robbins (P)2019 Audible Originals, LLC.<br/>"
}, {
    "author": ["Paulo Coelho"],
    "narratedBy": ["Trovi"],
    "genre": ["Novel", "Quest", "Drama", "Fantasy", "Adventure"],
    "reviews": [],
    "_id": "5f8fd1b6879113f1d3afe00d",
    "programType": "Audio-Book",
    "rating": null,
    "totalReviewPoint": 0,
    "totalReview": 0,
    "sampleUri": null,
    "bookUri": null,
    "listenerCount": 0,
    "length": 120,
    "language": "English",
    "publisher": "Trovi Publications",
    "category": "fiction",
    "title": "The Alchemist",
    "imageUri": "https://res.cloudinary.com/trovi/image/upload/v1602555353/theAlchemist_nnjxkr.jpg",
    "price": 500,
    "summary": " Paulo Coelho's enchanting novel has inspired a devoted following around the world. This story, dazzling in its simplicity and wisdom, is about an Andalusian shepherd boy named Santiago who travels from his homeland in Spain to the Egyptian desert in search of treasure buried in the Pyramids. Along the way he meets a Gypsy woman, a man who calls himself king, and an Alchemist, all of whom point Santiago in the direction of his quest. No one knows what the treasure is, or if Santiago will be able to surmount the obstacles along the way But what starts out as a journey to find worldly goods turns into a meditation on the treasures found within. Lush, evocative, and deeply humane, the story of Santiago is art eternal testament to the transforming power of our dreams and the importance of listening to our hearts.<br/> ©1988 Paulo Coelho (P)2005 HarperCollins Publishers"
}, {
    "author": ["Geoff White", "Bernard P. Achampong"],
    "narratedBy": ["Trovi"],
    "genre": ["Horror", "Crime Film", "Thriller", "Mystery"],
    "reviews": [],
    "_id": "5f8fd1b6879113f1d3afe00e",
    "programType": "Audio-Book",
    "rating": null,
    "totalReviewPoint": 0,
    "totalReview": 0,
    "sampleUri": null,
    "bookUri": null,
    "listenerCount": 0,
    "length": 120,
    "language": "English",
    "publisher": "Trovi Publications",
    "category": "fiction",
    "title": "The Dark Web",
    "imageUri": "https://res.cloudinary.com/trovi/image/upload/v1602555360/theDarkWeb_b0ozka.jpg",
    "price": 500,
    "summary": "From sex trafficking and fraud to government secrets and anonymous hacking groups, this definitive exploration and exposé of the dark web goes where no documentary has gone before. <br/> The anonymous and lawless online environment of the Dark Web makes headlines on a daily basis. It touches all of our lives, without our knowledge, in many different ways. But where do the myths end and reality begin? <br/> Tech writer and broadcaster Geoff White (Channel 4 News) wants to find out. He casts an investigatory light on the dark underworld of the internet. We join him on a shocking tour of its secrets, revealing corporate hackers, paedophile rings, fraud on an international scale, conspiracy theories, drug dealers, gun runners, spies and specialist police investigators.<br/>  Driven by undercover recordings, anonymous contributors and expert interviews, this in-depth, journalistically-rigorous current affairs investigation leaves no online stone unturned in its quest for the truth. <br/> This is an Audible Original Podcast. Free for members. You can download all 10 episodes to your Library now.<br/> ©2016 Audible, Ltd. (P)2016 Audible, Ltd.<br/>"
}, {
    "author": ["Neil Gaiman", "Dirk Maggs"],
    "narratedBy": ["Trovi"],
    "genre": ["Dark fantasy", "Dark Comedy", "Horror Comics"],
    "reviews": [],
    "_id": "5f8fd1b6879113f1d3afe00f",
    "programType": "Audio-Book",
    "rating": null,
    "totalReviewPoint": 0,
    "totalReview": 0,
    "sampleUri": null,
    "bookUri": null,
    "listenerCount": 0,
    "length": 120,
    "language": "English",
    "publisher": "Trovi Publications",
    "category": "fiction",
    "title": "The Sandman",
    "imageUri": "https://res.cloudinary.com/trovi/image/upload/v1602555357/theSandman_ekdjqy.jpg",
    "price": 1170,
    "summary": " Please note: This content is not for kids. It is for mature audiences only. Just like the original graphic novels, this audio adaptation contains explicit language and graphic violence, as well as strong sexual content and themes. Discretion is advised.<br/> Hailed by the Los Angeles Times Magazine as “the greatest epic in the history of comic books”, The Sandman changed the game with its dark, literary world of fantasy and horror - creating a global, cultural phenomenon in the process. At long last, Audible and DC present the first-ever audio production of the New York Times best-selling series written by acclaimed storyteller Neil Gaiman (who also serves as co-executive producer). Adapted and directed by multi-award-winner (and frequent Gaiman collaborator) Dirk Maggs, and performed by an ensemble cast with James McAvoy (It, Parts One and Two, X-Men: First Class, Split) in the title role, this first installment of a multi-part original audio series will transport you to a world that re-writes the rules of audio entertainment the way that The Sandman originally re-defined the graphic novel.<br/> When The Sandman, also known as Lord Morpheus - the immortal king of dreams, stories and the imagination - is pulled from his realm and imprisoned on Earth by a nefarious cult, he languishes for decades before finally escaping. Once free, he must retrieve the three “tools” that will restore his power and help him to rebuild his dominion, which has deteriorated in his absence. As the multi-threaded story unspools, The Sandman descends into Hell to confront Lucifer (Michael Sheen), chases rogue nightmares who have escaped his realm, and crosses paths with an array of characters from DC comic books, ancient myths, and real-world history, including: Inmates of Gotham City's Arkham Asylum, Doctor Destiny, the muse Calliope, the three Fates, William Shakespeare (Arthur Darvill), and many more. <br/> A powerhouse supporting cast helps translate this masterwork into a sonic experience worthy of its legacy, including Riz Ahmed, Kat Dennings, Taron Egerton, Samantha Morton, Bebe Neuwirth, Andy Serkis, and more. Setting the stage for their performance is an unprecedented cinematic soundscape featuring an original musical score by British Academy Award winner James Hannigan. Fans will especially revel in a new twist for the audio adaptation: Neil Gaiman himself serves as the narrator. Follow him as he leads listeners along a winding path of myths, imagination and, often, terror. Even in your wildest dreams, you’ve never heard anything like this.<br/> ©2020 DC. All Rights Reserved. The Sandman and all related elements are trademarks of DC Comics. (P)2020 DC Comics and Audible<br/>"
}, {
    "author": ["Robert T. Kiyosaki"],
    "narratedBy": ["Trovi"],
    "genre": ["Self-help", "Motivation", "Business"],
    "reviews": [],
    "_id": "5f8fd1b6879113f1d3afe010",
    "programType": "Audio-Book",
    "rating": null,
    "totalReviewPoint": 0,
    "totalReview": 0,
    "sampleUri": null,
    "bookUri": null,
    "listenerCount": 0,
    "length": 120,
    "language": "English",
    "publisher": "Trovi Publications",
    "category": "non-fiction",
    "title": "Rich Dad Poor Dad",
    "imageUri": "https://res.cloudinary.com/trovi/image/upload/v1602555357/richDadPoorDad_t31h71.jpg",
    "price": 837,
    "summary": "Rich Dad Poor Dad will….<br/> <br/> Explode the myth that you need to earn a high income to become rich<br/> Challenge the belief that your house is an asset<br/> Show parents why they can’t rely on the school system to teach their kids about money<br/> Define once and for all an asset and a liability<br/> Teach you what to teach your kids about money for their future financial success<br/> Robert Kiyosaki has challenged and changed the way tens of millions of people around the world think about money. With perspectives that often contradict conventional wisdom, Robert has earned a reputation for straight talk, irreverence, and courage. He is regarded worldwide as a passionate advocate for financial education.<br/> <br/> \"The main reason people struggle financially is because they have spent years in school but learned nothing about money. The result is that people learn to work for money… but never learn to have money work for them.\"<br/> —Robert Kiyosaki Rich Dad Poor Dad – The #1 Personal Finance Book of All Time!<br/> <br/> ©2011 by CASHFLOW Technologies, Inc. (P)2012 Brilliance Audio, all rights reserved.<br/>"
}, {
    "author": ["Alice Fraser", "Ash Ranpura"],
    "narratedBy": ["Trovi"],
    "genre": ["Self-help"],
    "reviews": [],
    "_id": "5f8fd1b6879113f1d3afe011",
    "programType": "Audio-Book",
    "rating": null,
    "totalReviewPoint": 0,
    "totalReview": 0,
    "sampleUri": null,
    "bookUri": null,
    "listenerCount": 0,
    "length": 120,
    "language": "English",
    "publisher": "Trovi Publications",
    "category": "non-fiction",
    "title": "Make Life Work",
    "imageUri": "https://res.cloudinary.com/trovi/image/upload/v1602555360/makeLifeWork_pmspcd.jpg",
    "price": 493,
    "summary": " These days it can feel like life is a never-ending to-do list, and it’s increasingly difficult to balance work and life. People everywhere are unhappy about their work-life balance, and we’re seeing growing numbers of people reporting burnout.<br/> <br/> Comedian and ex-lawyer Alice Fraser has experienced the costs of work-life imbalance first-hand, so she teams up with neuroscientist Ash Ranpura to look for solutions to the demands of modern life.<br/> <br/> They journey from the workplace, which is literally killing us, through to our smartphone, beds and even brains, to work out where we’re going wrong and find some science-based solutions.<br/> <br/> A Somethin’ Else production for Audible Originals.<br/> <br/> This is an Audible Original Podcast. Free for members. You can download all 6 episodes to your Library now.<br/> <br/> ©2020 Audible, Ltd. (P)2020 Audible, Ltd.<br/>"
}, {
    "author": ["Jay Shetty"],
    "narratedBy": ["Trovi"],
    "genre": ["Self-help"],
    "reviews": [],
    "_id": "5f8fd1b6879113f1d3afe012",
    "programType": "Audio-Book",
    "rating": null,
    "totalReviewPoint": 0,
    "totalReview": 0,
    "sampleUri": null,
    "bookUri": null,
    "listenerCount": 0,
    "length": 120,
    "language": "English",
    "publisher": "Trovi Publications",
    "category": "non-fiction",
    "title": "Think Like a Monk",
    "imageUri": "https://res.cloudinary.com/trovi/image/upload/v1602555360/thinkLikeAMonk_ifsjsi.jpg",
    "price": 1080,
    "summary": " These days it can feel like life is a never-ending to-do list, and it’s increasingly difficult to balance work and life. People everywhere are unhappy about their work-life balance, and we’re seeing growing numbers of people reporting burnout.<br/> <br/> Comedian and ex-lawyer Alice Fraser has experienced the costs of work-life imbalance first-hand, so she teams up with neuroscientist Ash Ranpura to look for solutions to the demands of modern life.<br/> <br/> They journey from the workplace, which is literally killing us, through to our smartphone, beds and even brains, to work out where we’re going wrong and find some science-based solutions.<br/> <br/> A Somethin’ Else production for Audible Originals.<br/> <br/> This is an Audible Original Podcast. Free for members. You can download all 6 episodes to your Library now.<br/> <br/> ©2020 Audible, Ltd. (P)2020 Audible, Ltd.<br/>"
}, {
    "author": ["Amish Tripathi"],
    "narratedBy": ["Trovi"],
    "genre": ["Saga", "Historical", "Alternate History", "Fantasy", "High Fantasy", "Mithic"],
    "reviews": [],
    "_id": "5f8fd1b6879113f1d3afe013",
    "programType": "Audio-Book",
    "rating": null,
    "totalReviewPoint": 0,
    "totalReview": 0,
    "sampleUri": null,
    "bookUri": null,
    "listenerCount": 0,
    "length": 120,
    "language": "English",
    "publisher": "Trovi Publications",
    "category": "fiction",
    "title": "Raavan : Enemy of Aryavarta",
    "imageUri": "https://res.cloudinary.com/trovi/image/upload/v1602555349/raavanEnemyOfAryavarta_cujcel.jpg",
    "price": 836,
    "summary": " These days it can feel like life is a never-ending to-do list, and it’s increasingly difficult to balance work and life. People everywhere are unhappy about their work-life balance, and we’re seeing growing numbers of people reporting burnout.<br/> <br/> Comedian and ex-lawyer Alice Fraser has experienced the costs of work-life imbalance first-hand, so she teams up with neuroscientist Ash Ranpura to look for solutions to the demands of modern life.<br/> <br/> They journey from the workplace, which is literally killing us, through to our smartphone, beds and even brains, to work out where we’re going wrong and find some science-based solutions.<br/> <br/> A Somethin’ Else production for Audible Originals.<br/> <br/> This is an Audible Original Podcast. Free for members. You can download all 6 episodes to your Library now.<br/> <br/> ©2020 Audible, Ltd. (P)2020 Audible, Ltd.<br/>"
}, {
    "author": ["Daniel Kahneman"],
    "narratedBy": ["Trovi"],
    "genre": ["Self-help", "Psychological"],
    "reviews": [],
    "_id": "5f8fd1b6879113f1d3afe014",
    "programType": "Audio-Book",
    "rating": null,
    "totalReviewPoint": 0,
    "totalReview": 0,
    "sampleUri": null,
    "bookUri": null,
    "listenerCount": 0,
    "length": 120,
    "language": "English",
    "publisher": "Trovi Publications",
    "category": "non-fiction",
    "title": "Thinking, Fast and Slow",
    "imageUri": "https://res.cloudinary.com/trovi/image/upload/v1602555356/thinkingFastAndSlow_nh3nor.jpg",
    "price": 1090,
    "summary": " These days it can feel like life is a never-ending to-do list, and it’s increasingly difficult to balance work and life. People everywhere are unhappy about their work-life balance, and we’re seeing growing numbers of people reporting burnout.<br/> <br/> Comedian and ex-lawyer Alice Fraser has experienced the costs of work-life imbalance first-hand, so she teams up with neuroscientist Ash Ranpura to look for solutions to the demands of modern life.<br/> <br/> They journey from the workplace, which is literally killing us, through to our smartphone, beds and even brains, to work out where we’re going wrong and find some science-based solutions.<br/> <br/> A Somethin’ Else production for Audible Originals.<br/> <br/> This is an Audible Original Podcast. Free for members. You can download all 6 episodes to your Library now.<br/> <br/> ©2020 Audible, Ltd. (P)2020 Audible, Ltd.<br/>"
}, {
    "author": ["James Clear"],
    "narratedBy": ["Trovi"],
    "genre": ["Self-help"],
    "reviews": [],
    "_id": "5f8fd1b6879113f1d3afe015",
    "programType": "Audio-Book",
    "rating": null,
    "totalReviewPoint": 0,
    "totalReview": 0,
    "sampleUri": null,
    "bookUri": null,
    "listenerCount": 0,
    "length": 120,
    "language": "English",
    "publisher": "Trovi Publications",
    "category": "non-fiction",
    "title": "Atomic Habits",
    "imageUri": "https://res.cloudinary.com/trovi/image/upload/v1602555348/atomicHabits_zbpo7v.jpg",
    "price": 888,
    "summary": " These days it can feel like life is a never-ending to-do list, and it’s increasingly difficult to balance work and life. People everywhere are unhappy about their work-life balance, and we’re seeing growing numbers of people reporting burnout.<br/> <br/> Comedian and ex-lawyer Alice Fraser has experienced the costs of work-life imbalance first-hand, so she teams up with neuroscientist Ash Ranpura to look for solutions to the demands of modern life.<br/> <br/> They journey from the workplace, which is literally killing us, through to our smartphone, beds and even brains, to work out where we’re going wrong and find some science-based solutions.<br/> <br/> A Somethin’ Else production for Audible Originals.<br/> <br/> This is an Audible Original Podcast. Free for members. You can download all 6 episodes to your Library now.<br/> <br/> ©2020 Audible, Ltd. (P)2020 Audible, Ltd.<br/>"
}, {
    "author": ["Benjamin Graham"],
    "narratedBy": ["Trovi"],
    "genre": ["Self-help", "Business"],
    "reviews": [],
    "_id": "5f8fd1b6879113f1d3afe016",
    "programType": "Audio-Book",
    "rating": null,
    "totalReviewPoint": 0,
    "totalReview": 0,
    "sampleUri": null,
    "bookUri": null,
    "listenerCount": 0,
    "length": 120,
    "language": "English",
    "publisher": "Trovi Publications",
    "category": "non-fiction",
    "title": "The Intelligent Investor Rev Ed.",
    "imageUri": "https://res.cloudinary.com/trovi/image/upload/v1602555355/theIntelligentInvestorRevEd_un3iwa.jpg",
    "price": 1829,
    "summary": " These days it can feel like life is a never-ending to-do list, and it’s increasingly difficult to balance work and life. People everywhere are unhappy about their work-life balance, and we’re seeing growing numbers of people reporting burnout.<br/> <br/> Comedian and ex-lawyer Alice Fraser has experienced the costs of work-life imbalance first-hand, so she teams up with neuroscientist Ash Ranpura to look for solutions to the demands of modern life.<br/> <br/> They journey from the workplace, which is literally killing us, through to our smartphone, beds and even brains, to work out where we’re going wrong and find some science-based solutions.<br/> <br/> A Somethin’ Else production for Audible Originals.<br/> <br/> This is an Audible Original Podcast. Free for members. You can download all 6 episodes to your Library now.<br/> <br/> ©2020 Audible, Ltd. (P)2020 Audible, Ltd.<br/>"
}
];
